### ISSUE TITLE
Running into errors

### ISSUE THREAD

**Issue by sagnikbanerjee15** [shubhamchandak94/Spring#1]
Hello, 

I am using your software to compress fastq files but I am running into the following error.

*** Preprocessing ***
../sagnik/softwares/SPRING/spring: line 52: /usr/bin/time: No such file or directory

The command I am running is nohup ../sagnik/softwares/SPRING/spring -c -1 18359_CI16151_Rar3_raw_data/s_1_1_sequence.txt -t 20 -q qvz -o 18359_CI16151_Rar3_raw_data/s_1_1_sequence.txt.spring -i

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello,

I got the error fixed. Replacing /usr/bin/time with just "time" fixed the issue.

Thank you.

**Comment by shubhamchandak94** [comment]
Closing because we have updated to new version.
