### ISSUE TITLE
recommended file extension

### ISSUE THREAD

**Issue by peterjc** [shubhamchandak94/Spring#11]
People are used to various compression convention like ``.gz`` for gzip. I see no such recommendation in the paper or README, not even in the examples.

I think adoption of spring would be greatly helped with a similar convention here, e.g. adding ``.spring`` or similar.

e.g. ``example.fastq`` vs ``example.fastq.gz`` vs ``example.fastq.spring``

**Comment by shubhamchandak94** [comment]
Hello Peter,
Thanks for the suggestion. I have now updated the examples in the README with the compressed file having .spring extension as a convention.
Regards,
Shubham

**Comment by peterjc** [comment]
Thanks. Given the current use of tar for the on disk format (see #12), perhaps ``example.fastq.spring.tar`` makes sense too?
