### ISSUE TITLE
document MAGIC number at start of spring files

### ISSUE THREAD

**Issue by peterjc** [shubhamchandak94/Spring#12]
The first few bytes of most binary file formats contain a format specific header which serves as a fingerprint for automatically classifying the file. This is often termed the magic number string. e.g.

https://en.wikipedia.org/wiki/List_of_file_signatures

It looks like your files start with 0x2e 0x2f 0x00 0x00 ...

**Comment by shubhamchandak94** [comment]
Hello Peter,
Thanks for the suggestions, it's a good point. Right now, a SPRING compressed file is nothing but a tar archive (which can be verified using the file command in linux). So it has the appropriate tar format (https://www.gnu.org/software/tar/manual/html_node/Standard.html) which has the MAGIC number string "ustar" somewhat later in the file.
We are planning to add some new features to SPRING in the near future and we might move away from the tar format. Then I'll add a magic number and versioning (while maintaining backward compatibility).
Regards,
Shubham

**Comment by peterjc** [comment]
That makes sense - it would be good to say in the README that currently Spring files are tar archives.

**Comment by shubhamchandak94** [comment]
I have now added a line to that effect. I'm leaving the recommended extension as .spring because .tar seems to imply that untarring the compressed file will give something useful/ which is not really true here.
