### ISSUE TITLE
New feature: just re-ordering the reads in FASTQ without compression

### ISSUE THREAD

**Issue by ndaniel** [shubhamchandak94/Spring#14]
The re-ordering of the reads in FASTQ files the way as it is done in SPRING and HARC is _incredibly_ and **really useful operation** for a lot of other things than compression of FASTQ files, like for example, extending the reads sequences, filling the gap for paired-end reads, etc.

Would be possible to add a new feature to SPRING such that it would write in the output just the re-ordered FASTQ file instead of compressing it (instead of compressing it and decompressing it)? Now the only way to do this is to compress the FASTQ file and decompress it.

**Comment by shubhamchandak94** [comment]
Thanks for the suggestion. I will look into it next week and let you know.

**Comment by shubhamchandak94** [comment]
Hi, I have added this feature to a new branch - [reorder only](https://github.com/shubhamchandak94/Spring/tree/reorder-only). It should be faster than compressing and then decompressing, since it removes several of the unnecessary steps.

**Comment by ndaniel** [comment]
Thanks!

**Comment by Malfoy** [comment]
Hi, I would be very interested by this feature applied to long reads.
Why is the reason behind the read length limitation ?

**Comment by shubhamchandak94** [comment]
The reordering of reads is done by Spring only for the short reads, so it made sense to expose this as a feature. The long read compression in Spring is mainly provided for convenience, but internally does not do a reordering - instead just passes the reads into a general-purpose compressor. A couple of recent long-read specific compressors might help you with this:
- https://github.com/qm2/NanoSpring
- https://github.com/refresh-bio/CoLoRd
