### ISSUE TITLE
Read of length 0 detected. Aborting...

### ISSUE THREAD

**Issue by kvn95ss** [shubhamchandak94/Spring#15]
First off, great tool for lossless compression of fastq files. Perfect candidate for archival of data.

We have a fastq pair which have many low quality reads. When I try to compress I get the error mentioned in the title. 

We have trimmed the fastq files using trimmomatic, but we want to compress the original file for archival. Is there any way to by-pass this behaviour, or would you recommend against using SPRING for this type of data?

**Comment by shubhamchandak94** [comment]
Hi,
I think SPRING can be easily extended to support 0 length reads, will try to get this done next week. 
Regards,
Shubham

**Comment by kvn95ss** [comment]
Thanks for the quick reply! Will wait for the next release. 
Hope you keep things heavily backward compatible.

**Comment by shubhamchandak94** [comment]
Hi,
SPRING should now work with length 0 reads (it actually supported them all along, I just had a check to be extra sure - but now I tested files with length 0 reads and it seems to work without issues).
Regards,
Shubham
