### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by samarth51** [shubhamchandak94/Spring#16]
Hi Shubham,
I am trying to install SPRING in Ubuntu 16.04LTS with cmake version 3.14.7

During Installation i get the error. Can you please look into the error and advice me how to proceed . You help would be highly appreciable. 

Thanks
Samarth 

CMake Error at boost-cmake/cmake/Modules/DownloadBoost.cmake:66 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/sgrh/tools/Spring-master/boost-cmake/boost_1_67_0.tar.xz.tmp]
      expected hash: [4256a98911fbc943f7d97aab5f14f2ecde5341d90c5c5441696b7d99425af8fd]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [1;"Unsupported protocol"]

**Comment by shubhamchandak94** [comment]
Hi Samarth,
Thanks for pointing this out. Apparently there is some issue with downloading the boost source via HTTPS on some systems. I have now resolved this by including the boost source archive in the github repo itself. Can you pull the latest version and try again?
Thanks,
Shubham

**Comment by shubhamchandak94** [comment]
You might need to remove the existing content in the build directory to avoid caching related issues.

**Comment by samarth51** [comment]
Thanks for your prompt response. I tried again and it was a success this time.

Now When I tried to compress the paired-end fastq files, got some error.

**Starting compression...
Preprocessing ...
terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::runtime_errorterminate called recursively
Aborted (core dumped)**

Can you please again advice me how to proceed from this point. Sorry to trouble you again and again

Thanks 
Samarth

**Comment by shubhamchandak94** [comment]
Hi Samarth,
I am happy to help. Some things you might try to diagnose this:
1. Run test script to verify a number of modes for a some small test cases. If you get an error in this, please send the output and I can take a look.
```bash
cd build/
rm -r tmp*
./../util/test_script.sh
```
2. Another possible issue might be related to disk write permission/disk space. Spring creates a temporary directory inside a directory specified by the -w option which is by default set to the place you call spring from. You should have (i) write permissions in this directory and (ii) have sufficient space (empty space = total size of fastq files suffices). 
3. The fastq file should satisfy the following (in the default spring mode): (i) at most 4.29 billion reads (total for the two files), (ii) read length at most 511, and (iii) the quality length should match the read sequence length for each read.

Any other information about the fastq file you are working with (number of reads/size/publicly available) might be helpful as well. Also the command you are using will be helpful to verify everything is alright.
Regards,
Shubham

**Comment by shubhamchandak94** [comment]
If the error is in the preprocess stage as seems to be the case, you can search for `std::runtime_error` in  https://github.com/shubhamchandak94/Spring/blob/master/src/preprocess.cpp, and see if any of the error messages make sense in your case (some of them I already covered in the previous comment).

**Comment by samarth51** [comment]
Hi Shubham,
Thanks for your prompt responses. I ran the above command (test_script.sh) and attaching the output here for your further evaluation. Kindly check the attachment.
[check.txt](https://github.com/shubhamchandak94/Spring/files/3885090/check.txt)


I am trying to compress paired-end fastq files generated from Illumina machine.
Number of reads R1,R2 :37203696

SPRING COMMAND 
./spring -c -i <R1.fastq.gz> <R2.fastq.gz> -o test.spring

Note: I have the write permission and sufficient space.

Thanks & Best

**Comment by shubhamchandak94** [comment]
Got it. You need a -g flag if your input is gzipped. Let me know if that works.

**Comment by samarth51** [comment]
Thanks shubham.

You were absolutely correct.  Previously I did not apply -g flag and got that error.

Now the program is working perfectly for my Illumina PE data.

Thanks for your help and patience.
