### ISSUE TITLE
Crash on some data

### ISSUE THREAD

**Issue by KirillKryukov** [shubhamchandak94/Spring#17]
Spring compression crashes on some data with "Not enough memory!" message. The machine (Ubuntu) has 128 GB of RAM, so physical RAM should not be an issue. The input data size is 6.5 GB.

I uploaded the test data here: [http://kirill.med.u-tokai.ac.jp/data/temp/spring-repro-1.fq.gz](http://kirill.med.u-tokai.ac.jp/data/temp/spring-repro-1.fq.gz) (0.9 GB compressed, 6.5 GB decompressed).

Spring command: `spring -c -i h.fq -o h.spring -w . -t 1 -l --no-quality`

Output:
```
Temporary directory: ./tmp.fa37JncCHr/
Long flag detected.
Starting compression...
Preprocessing ...
Not enough memory! Please check README file for more information.
terminate called after throwing an instance of 'std::runtime_error'
  what():  BSC error.
Aborted (core dumped)
```

Note the spring seems to work fine on other data (including much larger data) on the same machine.

Full steps to reproduce on Ubuntu machine:
```
cd /tmp
mkdir spring-repro-1
cd spring-repro-1
git clone https://github.com/shubhamchandak94/SPRING.git
cd SPRING
mkdir build
cd build
cmake ..
make
cd ../..
wget http://kirill.med.u-tokai.ac.jp/data/temp/spring-repro-1.fq.gz
gzip -dc spring-repro-1.fq.gz >h.fq
./SPRING/build/spring -c -i h.fq -o h.spring -w . -t 1 -l --no-quality
```

By the way, the message is confusing: "Not enough memory! Please check README file for more information." - the README.md file does not seem to have information relevant to this crash.

Let me know if you need more details.

**Comment by shubhamchandak94** [comment]
Hi,

Thanks for pointing this out! The error was related to some integer type related issue in the wrapper I wrote around the BSC compressor. The "Please check README" message actually referred to the libbsc README ([link](https://github.com/shubhamchandak94/Spring/tree/master/src/libbsc)) - but that doesn't say much about this either. Anyway, please check the latest commit and let me know if it works correctly now.

Unrelated: If you are working with the "-l" mode, you can change the NUM_READS_PER_BLOCK_LONG parameter [here](https://github.com/shubhamchandak94/Spring/blob/master/src/params.h#L36) to control the number of long reads compressed in a block. This can speed things up as blocks are compressed in parallel, and can also reduce the memory consumption in some cases. By default it's set to 10000, which is okay in general but might be too large for reads that are millions of bases long.

Regards,
Shubham

**Comment by KirillKryukov** [comment]
@shubhamchandak94, thanks for the quick fix! It seems to work now. Will let you know if I find any other problems.

Regarding the NUM_READS_PER_BLOCK_LONG, I'm not thrilled about re-compiling spring based on input data. Also I prefer auto-detection since I may not know read length in advance. But thanks for suggestion.
