### ISSUE TITLE
Compression fail with error "CRITICAL tar: .: file changed as we read it"

### ISSUE THREAD

**Issue by henningonsbring** [shubhamchandak94/Spring#21]
Do other users also get multiple compression jobs failing with error message `CRITICAL tar: .: file changed as we read it`? I am confident we have no processes that change the content of our fastq.gz files.

If other users got this error as well, perhaps a `--ignore-failed-read` flag should be added one of the tar commands somewhere in the code? This may sound risky for users that do have processes which change the content of the fastq files, but each user can add checksums like sha256 or md5 to the compression workflow.

**Comment by shubhamchandak94** [comment]
Hi, this seems be an issue with the last part of the compressor where it combines all the generated streams into a single tar file. These streams are kept in a temporary directory generated by Spring (the temporary directory's location can be set using `--working-dir`). Is it possible the temporary directory was modified or removed during Spring's execution?
Regards,
Shubham

**Comment by henningonsbring** [comment]
Hi, thank you for the reply. I can not find any reason to suspect that the temp directory is modified or deleted during spring execution. But if this error is never reported by anyone else then perhaps I should suspect that the error is on my end.

**Comment by shubhamchandak94** [comment]
If it’s a reproducible issue, I’ll be happy to take a look. Otherwise, we can close this.

**Comment by henningonsbring** [comment]
Unfortunately the error can be dealt with on our end by just re-running the same command again (i.e. it is difficult to reproduce). However, based on your response, my interpretation is that no other user has reported the same problem and therefore it is resonable to assume the error is not in the spring-code. We will find a work around.

Perhaps, if other people show up with the same problem you could ping me into the conversation.

Cheers

**Comment by jarvint12** [comment]
Hello,

We are experiencing the same error. I've conducted four tests using paired WES fastq files and three tests with a single WGS fastq file. In each case, the run terminates with the following tar error:

"--
Sizes of streams after compression:
Reads:        4808055115 bytes
Quality:      5915000330 bytes
ID:            262912416 bytes
tar: .: file changed as we read it
Creating tar archive ...Program terminated unexpectedly with error: Error occurred during tar archive generation.
Deleting temporary directory...
--"

After which the program prints allowed options. I have created my own testing directory, ensuring it remains unaltered during runs. I've executed the command within this directory, and even used the '**--working-dir**' option to explicitly specify this directory. Moreover, I've confirmed that the "tmp.*" directories are correctly generated in the designated test folder. Therefore, the temporary directory really should not have changed during the runs. Nevertheless, the error persists. However, it seems like the program does produce a SPRING file, which has the same md5sum as the original fastq file after decompression. But can we trust, that the program runs successfully, even if it returns an error? My commands are below.

```spring -c -i /path/to/WGS.fastq.gz -o /path/to/WGS.spring -g```
```spring -c -i /path/to/WES_R1.fastq.gz /path/to/WES_R2.fastq.gz -o /path/to/WES.spring -g```

**Comment by henningonsbring** [comment]
Thanks for letting me know @jarvint12 

We found a work around that was site specific, I do not really remember the details, but it was not pretty. Anyhow, I moved on to higher priority issues.

**Comment by jarvint12** [comment]
Hi @henningonsbring,

I believe I talked to your old colleague, and the suggested workaround involved increasing the allocated RAM and re-running the analysis whenever the error arises. However, based on our RAM logs and the amount of RAM allocated to your jobs, it appears that RAM may not be the root cause of the issue. Furthermore, your colleague found out that the problem has persisted on your end, but rerunning the analysis has helped. Unfortunately, in our case, re-running the analysis does not yield success, as it consistently leads to a crash.
