### ISSUE TITLE
Suitable for production use?

### ISSUE THREAD

**Issue by keiranmraine** [shubhamchandak94/Spring#22]
Hi, would you consider this code to be suitable for use in a production system?  So far I'm finding this to be the best contender for being able to truly recapitulate the input data and it could save a significant amount of storage and costs for our users.

Use would be within University of Cambridge and UK NHS research environments.

**Comment by shubhamchandak94** [comment]
Hi Keiran,
Thanks for your interest in Spring. We haven't heard of any issues with Spring for some time now, so I do think that it doesn't have any major bugs. But it's hard to guarantee anything. One thing you can do is to not delete the original file until you compress with Spring, decompress to raw fastq and compare to original (can use a checksum). The Spring decompression process is very straightforward and reproducible so if you succeed in decompression once you can be confident that there is no data loss. 
Another option is to consider commercial alternatives, some of which might have reduced/free charges for non-commercial use. A few options I know of are:
- Illumina ORA
- Petagene
- Genomsys 

Regards,
Shubham
