### ISSUE TITLE
Allow `--fast` gzip compression on decode

### ISSUE THREAD

**Issue by keiranmraine** [shubhamchandak94/Spring#23]
Generally the file will be transient and level-1 offers a considerable saving in time over 6, as well as significant temporary storage over uncompressed.

This is more important when the output will be a pair of files.

**Comment by shubhamchandak94** [comment]
Hi Kieran,
Thanks for the suggestion. I am on vacation at the moment but plan to add this feature by the end of July. I will also explore a few other ideas for improving decompression performance when writing to gzipped streams. 
Regards,
Shubham

**Comment by shubhamchandak94** [comment]
Hi Kieran,
I have created a new release of Spring and also updated it on bioconda. This replaces zlib with cloudflare zlib (a modern implementation that is compatible with zlib but runs about 2x faster), and also introduces the `--gzip-level` flag that allows one to select a different gzip level than the default 6. Hopefully this helps with writing to compressed gzip files during decompression, and should also speed up reading from gzipped files during compression.
Regards,
Shubham
