### ISSUE TITLE
How to calculate field-wise compression results

### ISSUE THREAD

**Issue by abhay1109** [shubhamchandak94/Spring#24]
Hi Shubham,

In the supplementary results of the SPRING paper (section 3,1), field-wise results are given for reads, quality, and identifier compression for both SPRING and FaStore. I would like to repeat the same for my data, but couldn't find any options in the spring --help menu or any relevant code in this repository to do this.  

Could you please provide the code for obtaining field-wise compression results or point me to a relevant resource to do this? 

Best,
Abhay Rastogi (IIT-D)

**Comment by shubhamchandak94** [comment]
Hi Abhay,
For both SPRING and FaStore, this information is printed as part of the outputted log. 

Spring outputs like:
```
Sizes of streams after compression: 
Reads:        4253199163 bytes
Quality:     23773871332 bytes
ID:            857699359 bytes
```

FaStore (see list of outputted streams later below):
quality: Quality + NQua
read id: ReadIdToken + ReadIdValue + NReadIdToken + NReadIdValue
dna sequence: all other streams

```
StreamSizes:
Flag 83790128
LettersX 370224216
Rev 53787484
HardReads 822211705
LzId 52766728
Shift 119531528
Match 64719431
MatchBinary 117440991
TreeShift 42522846
CMatch 2905035
CShift 76269579
CLetters 216254518
Quality 24858475628
ReadIdToken 55666551
ReadIdValue 3767844675
PE_Flag 80022109
PE_LettersX 1226772666
PE_Swap 55890057
PE_Hard 2818563077
PE_LzId 227176537
PE_Shift 246970238
PE_MatchRLE 80011593
PE_MatchBinary 200829825
NDna: 7711719
NQua: 9814928
NReadIdToken: 21886
NReadIdValue: 1530223
```
