### ISSUE TITLE
Errors related to read length

### ISSUE THREAD

**Issue by sarahhcarl** [shubhamchandak94/Spring#25]
Hi,

Thanks a lot for developing this tool! I am trying to use it to compress several sets of paired-end fastq files, but I keep getting errors related to read length. For example, on several sets of files I get the following:

`spring -c -i LC-PBMC-M5_1st/LUNGPBMCM51st5p_S1_L004_R1_001.fastq.gz LC-PBMC-M5_1st/LUNGPBMCM51st5p_S1_L004_R2_001.fastq.gz -o LUNGPBMCM51st5p_S1_L004_001.spring`

`Temporary directory: ./tmp.tzxlYvKWrO/
Starting compression...
Preprocessing ...
Max read length without long mode is Max read length without long mode is 511, but found read of length 597
511, but found read of length 593
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively`

For others I get an error stating that the read length is not equal to the quality length. 

The strange thing is, these are short-read files. R1 is 26bp and R2 is 91bp. If I run them through fastqc I get no outlier reads (they all have the same length), and if I just have a look at the first few reads there is nothing obviously strange, e.g.:

`@A00721:163:H7CH5DSXY:4:1101:2356:1000 2:N:0:GCCATTCC
CTGCCCAGCGGTATCCCAAAGCTGCAAACTGAAGGGAATGCCCAGCACCTCAAATCGTTCCATCTCGAAGTCCACTCCAATGGTGGCCTAG
+
F:FFFFFFFFFFF,FF:FFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF,F
@A00721:163:H7CH5DSXY:4:1101:2537:1000 2:N:0:GCCATTCC
ATTTTGGCCAGAGGCCCTCTTTTACTGAGAACAAAATGTGCGTAGAACATTGTTCTGGCTGGCTATGTAAACAGAAGAAAACCTTGCTCTC
+
FFFFFFFFF:F:F:FFFFFFF:,FFFFFFFFFF::FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFF,F::FFF,FFFFFFFF:FFFFF:F
@A00721:163:H7CH5DSXY:4:1101:2935:1000 2:N:0:GCCATTCC
GGTGTGGTGCCAGATCTTCTCCATGTCGTCCCAGTTGGTGACGATGCCATGCTCAATGGGGTACTTCAGGGTCAGGATGCCACGCTAGCTC
+
FF:F:FFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF,FF:FF:FFFFFFFFFFFFFFFFFFFFF:FFFFF:FF,F
@A00721:163:H7CH5DSXY:4:1101:3079:1000 2:N:0:GCCATTCC
CATCAACACCTTTAATCACACTCCTTTGAGCTTGATCACCCAATTTTTCTGACTCCTTAATAGCAATACAGGAAGGGATGATAAACAGTGG
+
FF:FFFFFFFF:F,FFFFF,FFFF,:F,F:FFFFFFFFFFFF,FFFF:FFFFFFFFFFFFF,FFFFFFF:FFFFFFFFFFFFF::F,FF,:`

These are files that I received from a collaborator, so I can't rule out some strange preprocessing step upstream. Is there any way to print out which read(s) is causing the problem, so that I can try to troubleshoot?

Thanks a lot for the help!
Best,
Sarah

**Comment by shubhamchandak94** [comment]
Hi Sarah,
Thanks for trying out Spring. To help me better understand the problem, can you please answer the following?
1. Have you used Spring on similar files (or even other files) before or is this the first time using it? 
2. Is the error reproducible, i.e., do you get the same error every time you run Spring on a file?
3. What is the system? (linux? linux distro, version?)
4. How did you install spring? If it's built from source, can you provide the git commit? If it's installed using conda, can you try running `conda list | grep spring` to find the version being used? This might help isolate the issue.
5. Is the dataset publicly accessible or something you can share with me? If not, is there a similar publicly available dataset where you see the same error?
Thanks,
Shubham

**Comment by sarahhcarl** [comment]
Hi Shubham, 

Thanks for the quick response! To answer your questions:

1. This is the first time that I try to use Spring, but a colleague of mine used it on similar files about a year ago and it apparently worked. Unfortunately he has now left our group.
2. The error appears to be reproducible - I get the same error when I run Spring on the same files, although I get slightly different (but related) errors on different files.
3. I'm running on a linux CentOS 7 system (actually a VM)
4. I installed it with conda, and this is the version:
```
(scairap_stable) [carl@ds-1 02]$ conda list | grep spring
spring                    1.1.0                h9f5acd7_0    bioconda
```
5. Unfortunately not :/ - the data are confidential at this point, and I haven't seen this problem on any publicly available datasets (though I also haven't tried)

Cheers,
Sarah

**Comment by shubhamchandak94** [comment]
Ohh! You need to specify the `-g` flag when compressing gzipped inputs (or when you want to decompress back to .gz). Sorry this is a bit unintuitive. I might fix this in a future release.
Regards,
Shubham

**Comment by sarahhcarl** [comment]
Oh, ha, thanks! I feel silly to have missed that one! 

It looks like it's working now. Some autodetection would be nice if you wanted to add it to a future release (as icing on the cake) :) 

Best,
Sarah
