### ISSUE TITLE
what does " Paired id match code " mean? 

### ISSUE THREAD

**Issue by bkbx** [shubhamchandak94/Spring#26]
When I 'm compressing R1.fq.gz R2.fq.gz , it prints "Paired id match code: 1" .
![图片](https://user-images.githubusercontent.com/18281003/194748911-80cefb40-ac20-465b-8400-d5593ee96a02.png)
Beg for your guidance, thanks!

**Comment by shubhamchandak94** [comment]
Hi,
Spring attempts to reduce the size needed to store read identifiers (also called read names) for paired end files. Often times, the paired reads have very similar read ids, with just a small difference. In such cases, Spring tries to identify a pattern and then only compress the read ids for the first file. The patterns are listed in the code here: https://github.com/shubhamchandak94/Spring/blob/master/src/util.cpp#L190. Specifically code 1 means the paired read ids look like `ARBITRARY_STRING/1` and `ARBITRARY_STRING/2`.
Regards,
Shubham

**Comment by bkbx** [comment]
信件已收到
