### ISSUE TITLE
Create an official docker image

### ISSUE THREAD

**Issue by xec-cm** [shubhamchandak94/Spring#28]
I was wondering if you are considering creating an official docker image?

Tanks

**Comment by shubhamchandak94** [comment]
Hi, 
No we don't right now. You can create one yourself by installing Spring with conda as described at https://github.com/shubhamchandak94/Spring#install-with-conda-on-linux, or building it from source.
Regards,
Shubham

**Comment by shubhamchandak94** [comment]
Closing issue. Please reopen if you have further questions.
