### ISSUE TITLE
Compress fasta sequences

### ISSUE THREAD

**Issue by sagnikbanerjee15** [shubhamchandak94/Spring#29]
Hello,

I was wondering if Spring could be used to compress fasta sequences. I have files that contain only nucleotide sequences and no quality scores.

Thank you.

**Comment by shubhamchandak94** [comment]
Yes, if you have a file like
```
@READ1
AGCTAGCTGATCGATGCATGCTACGTAC
@READ2
ATTATATCGTGTCTCTATATTGCTGAGCTA
...
```
you can use the `--fasta-input` during compression.

**Comment by sagnikbanerjee15** [comment]
Sounds good. How about only quality scores? Is that possible?

**Comment by shubhamchandak94** [comment]
No, you can’t do that with Spring. Spring, in its default mode, just uses BSC (https://github.com/IlyaGrebnov/libbsc) for compressing quality scores. I would suggest just trying that

**Comment by shubhamchandak94** [comment]
Closing issue. Please reopen if you have further questions.
