### ISSUE TITLE
Few other issues

### ISSUE THREAD

**Issue by sagnikbanerjee15** [shubhamchandak94/Spring#3]
Hello,

Here is a list of few other issues I encountered. 

1) At line 52, you are attempting to execute ./$harcdir/bin/preprocess.out. I do not have the program spring in my path. So I am providing the entire directory name to point to the file location. the '.' before $harcdir is attempting to search in an incorrect location.
2) The same issue crops up in lines 57, 58, 85, 86, 88, 91, 92, 97, 103, 108, 111, 116

Thank you.

**Comment by shubhamchandak94** [comment]
Closing because we have updated to new version.
