### ISSUE TITLE
Pipping a fastq file 

### ISSUE THREAD

**Issue by DrRLS** [shubhamchandak94/Spring#31]
Is it possible to pipe a fastq file with Spring?

I 'd like to use the binary thresholding  in the compression step to reduce the size of a fastq file, but I want to generate a converted fastq file, not a .spring file.  Is it possible to start from a `large.fastq`  and get a `small.fastq` in which the scores have been transformed to binary to reduce the file size?

**Comment by shubhamchandak94** [comment]
Hi Ricardo, if your aim is simply to bin the quality scores into a binary value, I don't think Spring is the right tool. I would suggest looking for other existing tools to manipulate fastq files, or to write your own short script for the purpose. You might be able to reuse some of the code in Spring for that, specifically https://github.com/shubhamchandak94/Spring/blob/4a1659504430f2ac768cc4c5ca2c459afb791e2d/src/preprocess.cpp#L107 and https://github.com/shubhamchandak94/Spring/blob/4a1659504430f2ac768cc4c5ca2c459afb791e2d/src/util.cpp#L182.

**Comment by DrRLS** [comment]
thank you. I just realized that it is probably not what I need. I am trying to generate fastq files similar to what NCBI is doing with the SRA-lite format and the resulting fastq files with a simplified scores.
