### ISSUE TITLE
Error when using XARGS

### ISSUE THREAD

**Issue by kabilov** [shubhamchandak94/Spring#32]
I try to use spring througth xargs.

function my_func() {
    # arg1 = R1
    # arg2 = options

    R1=$(basename $1)
    R2=${R1/_R1/_R2}
    name=${R1%_R1*}
    options=$2

    spring -c -g $options -o $name.spring -i $R1 $R2; echo
}

export -f my_funct

options="--num-threads 8"
`echo ${files[*]} |xargs -d" " -I{} -n1 -P$num bash -c 'my_func "$@"' _ {} "$options"`

And for some fastq.gz files the following error is thrown:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot create temporary directory.
environment: line 1: 25179 Aborted                 (core dumped) spring -c -g $options -o $name.spring -i $R1 $R2

It appears that this issue only occurs when running the script on a remote drive.
The same fastq files on the local drive don't throw the error.

**Comment by shubhamchandak94** [comment]
Hi @kabilov, can you try using the `-w` flag that allows you to set the working directory where Spring creates the temporary directory it works in? Any directory where you have read/write access is good (perhaps don't use /tmp/ since it's on RAM and might use too much of it).

**Comment by kabilov** [comment]
Hi @shubhamchandak94
Thank you for reply.

I tried using the -w flag to set the working folder to the local drive, but that didn't help.
I also want to add that sometimes this error does not appear.

Is there a possibility that the name of tmp folder is the same for different files?

**Comment by shubhamchandak94** [comment]
I think this is due to a race condition situation in the Spring code where it generates a random string and checks if it exists, and if not it tries to create a directory. If multiple instances are running it's possible that a directory of the same name is created between the check and the creation of the directory. I will look into this and try to fix over the next few days (will need a few more days after that to get the update into conda).

Quick question: how many files are you working with?

**Comment by kabilov** [comment]
In the test, 3 pairs of fastq files were compressed.

I usually use tmp name with nanoseconds time: tmp_$(date +%H:%M:%S:%N)

**Comment by shubhamchandak94** [comment]
I just pushed a fix attempt, can you try it out and see if it fixes the issue? If so, I will also update on bioconda. Thanks!

**Comment by kabilov** [comment]
I checked the corrected Spring, the error disappeared.
Thank you for your help.
