### ISSUE TITLE
MD5 values are different

### ISSUE THREAD

**Issue by duronxx** [shubhamchandak94/Spring#35]
The compression rate of the software is great. During the test, the same parameters were used to compress the Fastq file. When the parameters and machine configuration were exactly the same, why were the MD5 values ​​different between the two times? Lossless compression is used

**Comment by JPWerling** [comment]
We've seen similar results in our reruns on the same sample using the same input parameters.
We ran the same inputs with the same parameters specifying 1 thread and yielded 20 identical outputs.
Ran the same inputs but with 2 threads and yielded different outputs.

If you unpack them you should have the same results regardless, ie lossless.

**Comment by shubhamchandak94** [comment]
Spring does not guarantee same compressed file when using multiple threads. This is because multiple threads compete to find matching reads and depending on how locks are obtained, you can get different set of reads matched per thread. It is still lossless.
