### ISSUE TITLE
loss in the compression of .gz files

### ISSUE THREAD

**Issue by Cimorgh-IT** [shubhamchandak94/Spring#36]
I used spring -c to compress with default options a PE fastq.gz files . then I used spring -d option to decompress them to fastq.gz file. the size of decompressed files are smaller than the original files and also the md5sum is different for both forward and reverse reads. it seem in the compression process it automatically eliminates some reads. But there was not such a problem in compression of fastq files and it was lossless.
Which paramater should i enter to use it for .gz files in lossless mode? --gzip-level?

**Comment by shubhamchandak94** [comment]
Please see https://github.com/shubhamchandak94/Spring/issues/30#issuecomment-1465074665. It is hard to reproduce the same exact gzip file and we do not attempt to do so. If you were to check the hash of the fastq file itself (e.g., zcat file.gz | md5sum) then you should find that the underlying fastq remains the same. So no reads should be lost.
