### ISSUE TITLE
How to work with spring compression in C++

### ISSUE THREAD

**Issue by foriin** [shubhamchandak94/Spring#37]
Hi and thanks for developing Spring,
I was wondering, is it possible to work with spring format using C++ without first decompressing it? When using gzip or bz2 compression I'm using boost:iostreams zlib and bz2lib to work directly in my cpp scripts. Is there a way to do something like that with Spring? Or is there a zcat analog that I can use to pipe .spring file to my script?
Cheers,
Artem

**Comment by shubhamchandak94** [comment]
Not really at the moment. One option I can imagine is to invoke spring with named pipes instead of files and then read from the pipe from your application in a streaming manner.
