### ISSUE TITLE
Support for gzipped Fastq (.fastq.gz)

### ISSUE THREAD

**Issue by Phillip-a-richmond** [shubhamchandak94/Spring#6]
Hello,
Do you support compression from .fastq.gz (gzipped fastq)? Or do you recommend unzipping and then running SPRING?

Thanks,
Phil

**Comment by shubhamchandak94** [comment]
SPRING currently does not support compression directly from gzipped fastq. So you will need to unzip and then run SPRING. 
I hope to add this feature to SPRING very soon.

**Comment by shubhamchandak94** [comment]
Hi Phil,
SPRING now supports compression from .fastq.gz.
Regards,
Shubham
