### ISSUE TITLE
Additional 'A' in FastQ Sequence

### ISSUE THREAD

**Issue by leonschuetz** [shubhamchandak94/Spring#7]
Hello,
I think I found a bug in your software:
If you use FastQ files which are generated on Windows (CR LF line ending) the decompressed FastQ files contain a additional 'A' at the end of each sequence.

Best Regards,
Leon Schütz

**Comment by shubhamchandak94** [comment]
Hi Leon,
Thanks for raising this issue. I have fixed it now, but note that the decompressed file will contain just the LF (\n) characters instead of CR LF (\r\n) and hence won't exactly match the input file.
Let me know if you run into any other issues.
Regards,
Shubham

**Comment by leonschuetz** [comment]
If the sequence is correct its fine.

Best Regards,
Leon
