### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by ZekunYin** [shubhamchandak94/Spring#9]
Hi,
I find SPRING a really wonderful work. And besides the compression ratio, I think the compression and decompression speed are also important. So have you ever benchmarked SPRING and other tools such as DSRC2? In my test, DSRC2 is able to compress 1GB of FASTQ file in less than one second.
Best,
Zekun

**Comment by shubhamchandak94** [comment]
Hi Zekun,

You can find detailed comparison with DSRC 2 and other tools in the supplementary material of the paper [here](https://academic.oup.com/bioinformatics/article/35/15/2674/5232998?guestAccessKey=266a1378-4684-4f04-bb99-6febdf9d1fb9). See tables 4 and 6 in the supplementary data.

Some ballpark numbers: SPRING is quite a bit slower than DSRC 2 in compression (at least 10 times slower), but is not that bad in terms of decompression (2-3 times slower). Of course, SPRING achieves as much as 4 times better compression on the NovaSeq datasets as compared to DSRC2, and is comparable in speed to the other compressors with good compression performance (like FaStore).

Regards,
Shubham

**Comment by ZekunYin** [comment]
thx a lot, I will read the supplement and do further test.
